---
title: "Data Visualization"
author: "Arga"
date: "1/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(sf)
library(scales)
library(ggtext)
```

# Data

```{r message=FALSE}
plastics <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-26/plastics.csv')

glimpse(plastics)
```

```{r}
world_map <- st_read("Igismap/")
```

```{r}
df_agg <- plastics %>% 
  group_by(year, country, num_events, volunteers) %>% 
  summarise(grand_total = sum(grand_total, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(country) %>% 
  group_by(country) %>% 
  mutate(trash_up = ifelse(lag(grand_total) < grand_total, "up", "down"),
         vol_up = ifelse(lag(volunteers) < volunteers, "up", "down"),
         trash_per_vol = grand_total/volunteers
         ) %>% 
  replace_na(list(trash_up = "just started",
                  vol_up = "just started"
                  )
             ) %>% 
  ungroup() %>% 
  filter(year == 2020) %>% 
  mutate(
    category = ifelse(trash_up == "just started", trash_up, paste(trash_up, vol_up))
         )

df_agg %>% 
  arrange(trash_per_vol) %>% 
  drop_na() %>% 
  slice(c(1:3, (nrow(.)-2):nrow(.)))
```

```{r}
df_agg %>% 
  filter(!country %in% world_map$name)
```

```{r}
df_map <- df_agg %>% 
  mutate(
    country = case_when(str_detect(country, "Korea") ~ "Korea, Republic of",
                        str_detect(country, "Tanzania") ~ "United Republic of Tanzania",
                        str_detect(country, "United Kingdom") ~ "United Kingdom",
                        str_detect(country, "United States of America") ~ "United States",
                        str_detect(country, "Vietnam") ~ "Viet Nam",
                        TRUE ~ country
                        )
  ) 

df_map <- world_map %>% 
  left_join(df_map, by = c("name" = "country")) %>% 
  st_as_sf()
```

```{r}
df_map %>% 
  ggplot() +
  geom_sf(aes(fill = category), color = "white", lty = "dashed", lwd = 0.1, show.legend = F) +
  scale_fill_manual(values = c("lightgreen", "green3", "steelblue", "firebrick4", "sienna3"), 
                    na.value = "#1D2024") +
  
# Just Stared
  geom_rect(aes(xmin = -155, xmax = -165, ymin = -50, ymax = -60), 
            fill = "steelblue", 
            inherit.aes = F) +
  geom_text(aes(x = -152, y = -55, label = "Just Started in 2020"), 
            size = 3.5, hjust = 0,
            inherit.aes = F, data = data.frame()) +
  
  # Matrix Legend
  geom_text(aes(x = -130, y = -35, label = "Count of Trash Over Year"),
            size = 3.5, hjust = 1,
            inherit.aes = F, data = data.frame()
            ) +
  geom_text(aes(x = -175, y = -20, label = "Number of Volunteers\n Over Year"),
            size = 3.5, angle = 90, hjust = 0,
            inherit.aes = F, data = data.frame()
            ) +
  geom_rect(aes(xmin = -150, xmax = -165, ymin = -10, ymax = -25), 
            fill = "lightgreen", 
            inherit.aes = F) +
  geom_rect(aes(xmin = -150, xmax = -165, ymin = 5, ymax = -10), 
            fill = "green3", 
            inherit.aes = F) +
    geom_rect(aes(xmin = -135, xmax = -150, ymin = -10, ymax = -25), 
            fill = "firebrick4", 
            inherit.aes = F) +
  geom_rect(aes(xmin = -135, xmax = -150, ymin = 5, ymax = -10), 
            fill = "sienna3", 
            inherit.aes = F) +
  geom_segment(aes(x = -167.5, xend = -125, y = -30, yend = -30 ),
               arrow = arrow(ends = "last", unit(10, units = "mm"), 
                             type = "closed")
               ) +
  geom_segment(aes(x = -167.5, xend = -167.5, y = -30, yend = 15 ),
               arrow = arrow(ends = "last", unit(10, units = "mm"), 
                             type = "closed")
               ) +
  labs(title = "Break Free From Plastic 2020",
       subtitle = "The color indicate the number of collected trash and the number of volunteers compared to the data from 2019. In some countries the campaign have collected <br> more trash in 2020 but with decreased number of volunteers, some have increased volunteers but found lower trash, and some events are just started in 2020. <br> <b style='color:firebrick4'> Vietnam</b>, <b style='color:firebrick4'> Kuwait</b>, and <b style='color:firebrick4'> Germany </b> are top 3 countries with the highest trash-to-volunteer ratio while <b style='color:dodgerblue4'> UAE</b>, <b style='color:dodgerblue4'> Honduras</b> , and <b style='color:dodgerblue4'> Greece </b> have lowest trash-to-volunteer ratio in 2020.",
       caption = "@Argaadya") +
  theme_void() +
  theme(legend.position = "top",
        plot.title = element_text(size = 24, hjust = 0.05),
        plot.subtitle = element_markdown(hjust = 0.5, size = 14, lineheight = unit(1.5, "mm"))
        )

ggsave("plasticmap.png", width = 16, height = 9)
```



